# Generated by Django 5.0.6 on 2024-07-04 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celulares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passo', models.IntegerField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='reparos/')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_ligando', models.BooleanField()),
                ('liga_vibra_som_sem_imagem', models.BooleanField()),
                ('liga_sem_carregar', models.BooleanField()),
                ('conector_quebrado', models.BooleanField()),
                ('tela_quebrada', models.BooleanField()),
                ('tampa_traseira_quebrada', models.BooleanField()),
                ('esta_mudo', models.BooleanField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celulares.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celulares.modelo')),
            ],
        ),
    ]
